# Generated by Django 5.1.5 on 2025-01-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_material_status_alter_sample_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='Material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.material'),
        ),
    ]
