# Generated by Django 5.1.5 on 2025-01-25 19:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_sample_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='Status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.status'),
            preserve_default=False,
        ),
    ]
