# Generated by Django 5.1.5 on 2025-01-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_sample_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='CreatedDt',
        ),
    ]
