# Generated by Django 5.1.5 on 2025-01-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_status_createddt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-Identifier']},
        ),
        migrations.RemoveField(
            model_name='sample',
            name='CreatedDt',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='Material',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='Priority',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='SampleDt',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='Status',
        ),
    ]
