# Generated by Django 5.1.5 on 2025-01-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_sample_options_remove_sample_createddt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
