# Generated by Django 5.1.5 on 2025-01-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_delete_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='CreatedDt',
        ),
    ]
