# Generated by Django 5.1.5 on 2025-01-25 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_material_createddt'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('UserText1', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.status')),
            ],
            options={
                'ordering': ['-Identifier'],
            },
        ),
    ]
