# Generated by Django 5.1.1 on 2025-02-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='Material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.material'),
        ),
    ]
